/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lists Categories
         * @description Lists all categories
         */
        get: operations["categories_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lists Comments
         * @description Paginated listing of all comments
         */
        get: operations["comments_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encode_profiles/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Encoding Profiles
         * @description Lists all encoding profiles for videos
         */
        get: operations["encode_profiles_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login url
         * @description Login url endpoint. According to what the portal provides, you may provide username and/or email, plus the password
         */
        post: operations["login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manage_comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Manage Comments
         * @description Manage comments for MediaCMS managers and reviewers
         */
        get: operations["manage_comments_list"];
        put?: never;
        post?: never;
        /**
         * Delete Comments
         * @description Delete comments for MediaCMS managers and reviewers
         */
        delete: operations["manage_comments_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manage_media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Manage Media
         * @description Manage media for MediaCMS managers and reviewers
         */
        get: operations["manage_media_list"];
        put?: never;
        post?: never;
        /**
         * Delete Media
         * @description Delete media for MediaCMS managers and reviewers
         */
        delete: operations["manage_media_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manage_users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Manage Users
         * @description Manage users for MediaCMS managers and reviewers
         */
        get: operations["manage_users_list"];
        put?: never;
        post?: never;
        /**
         * Delete Users
         * @description Delete users for MediaCMS managers
         */
        delete: operations["manage_users_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Media listings views */
        get: operations["media_list"];
        put?: never;
        /**
         * Add new Media
         * @description Adds a new media, for authenticated users
         */
        post: operations["media_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Media listings views */
        get: operations["media_list"];
        put?: never;
        /**
         * Add new Media
         * @description Adds a new media, for authenticated users
         */
        post: operations["media_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/user/bulk_actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Perform bulk actions on media
         * @description Perform various bulk actions on multiple media items at once
         */
        post: operations["media_user_bulk_actions_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/user/bulk_actions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Perform bulk actions on media
         * @description Perform various bulk actions on multiple media items at once
         */
        post: operations["media_user_bulk_actions_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{friendly_token}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                friendly_token: string;
            };
            cookie?: never;
        };
        /**
         * Get information for Media
         * @description Get information for a media
         */
        get: operations["media_read"];
        /**
         * Update Media
         * @description Update a Media, for Media uploader
         */
        put: operations["media_update"];
        /**
         * Run action on Media
         * @description Actions for a media, for MediaCMS editors and managers
         */
        post: operations["media_manager_actions"];
        /**
         * Delete Media
         * @description Delete a Media, for MediaCMS editors and managers
         */
        delete: operations["media_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{friendly_token}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                friendly_token: string;
            };
            cookie?: never;
        };
        /**
         * to_be_written
         * @description to_be_written
         */
        get: operations["media_actions_list"];
        put?: never;
        /**
         * to_be_written
         * @description to_be_written
         */
        post: operations["media_actions_create"];
        /**
         * to_be_written
         * @description to_be_written
         */
        delete: operations["media_actions_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{friendly_token}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                friendly_token: string;
            };
            cookie?: never;
        };
        /**
         * to_be_written
         * @description to_be_written
         */
        get: operations["media_comments_list"];
        put?: never;
        /**
         * to_be_written
         * @description to_be_written
         */
        post: operations["media_comments_create"];
        /**
         * to_be_written
         * @description to_be_written
         */
        delete: operations["media_comments_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{friendly_token}/comments/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                friendly_token: string;
                uid: string;
            };
            cookie?: never;
        };
        /**
         * to_be_written
         * @description to_be_written
         */
        get: operations["media_comments_read"];
        put?: never;
        /**
         * to_be_written
         * @description to_be_written
         */
        post: operations["media_comments_create"];
        /**
         * to_be_written
         * @description to_be_written
         */
        delete: operations["media_comments_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * to_be_written
         * @description to_be_written
         */
        get: operations["playlists_list"];
        put?: never;
        /**
         * to_be_written
         * @description to_be_written
         */
        post: operations["playlists_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playlists/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * to_be_written
         * @description to_be_written
         */
        get: operations["playlists_list"];
        put?: never;
        /**
         * to_be_written
         * @description to_be_written
         */
        post: operations["playlists_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playlists/{friendly_token}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                friendly_token: string;
            };
            cookie?: never;
        };
        /**
         * to_be_written
         * @description to_be_written
         */
        get: operations["playlists_read"];
        /**
         * to_be_written
         * @description to_be_written
         */
        put: operations["playlists_update"];
        /**
         * to_be_written
         * @description to_be_written
         */
        post: operations["playlists_create"];
        /**
         * to_be_written
         * @description to_be_written
         */
        delete: operations["playlists_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * to_be_written
         * @description to_be_written
         */
        get: operations["search_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lists Tags
         * @description Paginated listing of all tags
         */
        get: operations["tags_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/action/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action: string;
            };
            cookie?: never;
        };
        /**
         * List user actions
         * @description Lists user actions
         */
        get: operations["user_action_read"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a user token
         * @description Returns an authenticated user's token
         */
        get: operations["user_token_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users
         * @description Paginated listing of users
         */
        get: operations["users_list"];
        put?: never;
        /**
         * Create user
         * @description Create a new user. Only for managers.
         */
        post: operations["users_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users
         * @description Paginated listing of users
         */
        get: operations["users_list"];
        put?: never;
        /**
         * Create user
         * @description Create a new user. Only for managers.
         */
        post: operations["users_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        /**
         * List user details
         * @description Get user details
         */
        get: operations["users_read"];
        /**
         * Update user details
         * @description Allows a user to change their password. Allows a manager to approve a user.
         */
        put: operations["users_update"];
        /**
         * Edit user details
         * @description Post user details - authenticated view
         */
        post: operations["users_create"];
        /**
         * to_be_written
         * @description to_be_written
         */
        delete: operations["users_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{username}/contact": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Contact user
         * @description Contact user through email, if user has set this option
         */
        post: operations["users_contact_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whoami user information
         * @description Whoami user information
         */
        get: operations["whoami_read"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Category: {
            /** Title */
            title: string;
            /** Uid */
            uid?: string;
            /** Description */
            description?: string;
            /**
             * Is global
             * @description global categories or user specific
             */
            is_global?: boolean;
            /**
             * Media count
             * @description number of media
             */
            media_count?: number;
            /** User */
            readonly user?: string;
            /** Thumbnail url */
            readonly thumbnail_url?: string;
        };
        Comment: {
            /**
             * Add date
             * Format: date-time
             */
            readonly add_date?: string;
            /**
             * Text
             * @description text
             */
            text: string;
            /** Parent */
            parent?: number | null;
            /** Author thumbnail url */
            readonly author_thumbnail_url?: string;
            /** Author profile */
            readonly author_profile?: string;
            /** Author name */
            readonly author_name?: string;
            /** Media url */
            readonly media_url?: string;
            /**
             * Uid
             * Format: uuid
             */
            readonly uid?: string;
        };
        EncodeProfile: {
            /** Name */
            name: string;
            /**
             * Extension
             * @enum {string}
             */
            extension: "mp4" | "webm" | "gif";
            /**
             * Resolution
             * @enum {integer|null}
             */
            resolution?: 2160 | 1440 | 1080 | 720 | 480 | 360 | 240 | 144 | null;
            /**
             * Codec
             * @enum {string|null}
             */
            codec?: "h265" | "h264" | "vp9" | null;
            /**
             * Description
             * @description description
             */
            description?: string;
        };
        Login: {
            /** Email */
            email?: string;
            /** Username */
            username?: string;
            /** Password */
            password: string;
            /** Token */
            token?: string;
        };
        Media: {
            /**
             * Friendly token
             * @description Identifier for the Media
             */
            readonly friendly_token?: string;
            /** Url */
            readonly url?: string;
            /** Api url */
            readonly api_url?: string;
            /** User */
            readonly user?: string;
            /**
             * Title
             * @description media title
             */
            title?: string;
            /** Description */
            description?: string;
            /**
             * Date produced
             * Format: date-time
             */
            readonly add_date?: string | null;
            /** Views */
            readonly views?: number;
            /**
             * Media type
             * @enum {string}
             */
            readonly media_type?: "video" | "image" | "pdf" | "audio";
            /**
             * State
             * @description state of Media
             * @enum {string}
             */
            readonly state?: "private" | "public" | "unlisted";
            /** Duration */
            readonly duration?: number;
            /** Thumbnail url */
            readonly thumbnail_url?: string;
            /**
             * Is reviewed
             * @description Whether media is reviewed, so it can appear on public listings
             */
            readonly is_reviewed?: boolean;
            /** Preview url */
            readonly preview_url?: string;
            /** Author name */
            readonly author_name?: string;
            /** Author profile */
            readonly author_profile?: string;
            /** Author thumbnail */
            readonly author_thumbnail?: string;
            /**
             * Encoding status
             * @enum {string}
             */
            readonly encoding_status?: "pending" | "running" | "fail" | "success";
            /** Likes */
            readonly likes?: number;
            /** Dislikes */
            readonly dislikes?: number;
            /**
             * Reported times
             * @description how many time a media is reported
             */
            readonly reported_times?: number;
            /**
             * Featured
             * @description Whether media is globally featured by a MediaCMS editor
             */
            readonly featured?: boolean;
            /**
             * User featured
             * @description Featured by the user
             */
            user_featured?: boolean;
            /**
             * Size
             * @description media size in bytes, automatically calculated
             */
            readonly size?: string | null;
        };
        SingleMedia: {
            /** Url */
            readonly url?: string;
            /** User */
            readonly user?: string;
            /**
             * Title
             * @description media title
             */
            title?: string;
            /** Description */
            description?: string;
            /**
             * Date produced
             * Format: date-time
             */
            readonly add_date?: string | null;
            /**
             * Edit date
             * Format: date-time
             */
            readonly edit_date?: string;
            /**
             * Media type
             * @enum {string}
             */
            readonly media_type?: "video" | "image" | "pdf" | "audio";
            /**
             * State
             * @description state of Media
             * @enum {string}
             */
            readonly state?: "private" | "public" | "unlisted";
            /** Is shared */
            readonly is_shared?: string;
            /** Duration */
            readonly duration?: number;
            /** Thumbnail url */
            readonly thumbnail_url?: string;
            /** Poster url */
            readonly poster_url?: string;
            /**
             * Thumbnail time
             * @description Time on video that a thumbnail will be taken
             */
            thumbnail_time?: number | null;
            /** Sprites url */
            readonly sprites_url?: string;
            /** Preview url */
            readonly preview_url?: string;
            /** Author name */
            readonly author_name?: string;
            /** Author profile */
            readonly author_profile?: string;
            /** Author thumbnail */
            readonly author_thumbnail?: string;
            /** Encodings info */
            readonly encodings_info?: string;
            /**
             * Encoding status
             * @enum {string}
             */
            readonly encoding_status?: "pending" | "running" | "fail" | "success";
            /** Views */
            readonly views?: number;
            /** Likes */
            readonly likes?: number;
            /** Dislikes */
            readonly dislikes?: number;
            /**
             * Reported times
             * @description how many time a media is reported
             */
            readonly reported_times?: number;
            /**
             * User featured
             * @description Featured by the user
             */
            user_featured?: boolean;
            /** Original media url */
            readonly original_media_url?: string;
            /**
             * Size
             * @description media size in bytes, automatically calculated
             */
            readonly size?: string | null;
            /** Video height */
            readonly video_height?: number;
            /**
             * Enable comments
             * @description Whether comments will be allowed for this media
             */
            enable_comments?: boolean;
            /** Categories info */
            readonly categories_info?: string;
            /**
             * Is reviewed
             * @description Whether media is reviewed, so it can appear on public listings
             */
            readonly is_reviewed?: boolean;
            /** Edit url */
            readonly edit_url?: string;
            /** Tags info */
            readonly tags_info?: string;
            /** Hls info */
            readonly hls_info?: string;
            /** License */
            license?: number | null;
            /** Subtitles info */
            readonly subtitles_info?: string;
            /** Chapter data */
            readonly chapter_data?: string;
            /** Ratings info */
            readonly ratings_info?: string;
            /** Add subtitle url */
            readonly add_subtitle_url?: string;
            /**
             * Allow download
             * @description Whether option to download media is shown
             */
            allow_download?: boolean;
            /** Slideshow items */
            readonly slideshow_items?: string;
        };
        Playlist: {
            /** ID */
            readonly id?: number;
            /**
             * Add date
             * Format: date-time
             */
            readonly add_date?: string;
            /** Title */
            title: string;
            /**
             * Description
             * @description description
             */
            description?: string;
            /** User */
            readonly user?: string;
            /** Media count */
            readonly media_count?: string;
            /** Url */
            readonly url?: string;
            /** Api url */
            readonly api_url?: string;
            /** Thumbnail url */
            readonly thumbnail_url?: string;
            /** Friendly token */
            friendly_token?: string;
        };
        Tag: {
            /** Title */
            title: string;
            /**
             * Media count
             * @description number of media
             */
            media_count?: number;
            /** Thumbnail url */
            readonly thumbnail_url?: string;
        };
        User: {
            /** About me */
            description?: string;
            /**
             * Date added
             * Format: date-time
             */
            readonly date_added?: string;
            /** Full name */
            name: string;
            /** Is featured */
            readonly is_featured?: boolean;
            /** Thumbnail url */
            readonly thumbnail_url?: string;
            /** Url */
            readonly url?: string;
            /** Api url */
            readonly api_url?: string;
            /**
             * Username
             * @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
             */
            readonly username?: string;
            /** Advanced user */
            readonly advancedUser?: boolean;
            /** MediaCMS Editor */
            readonly is_editor?: boolean;
            /** MediaCMS Manager */
            readonly is_manager?: boolean;
            /** Email is verified */
            readonly email_is_verified?: string;
        };
        UserDetail: {
            /** About me */
            description?: string;
            /**
             * Date added
             * Format: date-time
             */
            readonly date_added?: string;
            /** Full name */
            name?: string;
            /** Is featured */
            readonly is_featured?: boolean;
            /** Thumbnail url */
            readonly thumbnail_url?: string;
            /** Banner thumbnail url */
            readonly banner_thumbnail_url?: string;
            /** Url */
            readonly url?: string;
            /**
             * Username
             * @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
             */
            readonly username?: string;
            /** Media info */
            readonly media_info?: string;
            /** Api url */
            readonly api_url?: string;
            /** Edit url */
            readonly edit_url?: string;
            /** Default channel edit url */
            readonly default_channel_edit_url?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: {
        users_createData: {
            content: {
                "application/json": {
                    username: string;
                    password: string;
                    /** Format: email */
                    email: string;
                    name: string;
                };
            };
        };
        media_create: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description media_file
                     */
                    media_file: string;
                    /** @description description */
                    description?: string;
                    /** @description title */
                    title?: string;
                };
            };
        };
        media_user_bulk_actions_createData: {
            content: {
                "application/json": {
                    /** @description List of media IDs */
                    media_ids: string[];
                    /**
                     * @description Action to perform
                     * @enum {string}
                     */
                    action: "enable_comments" | "disable_comments" | "delete_media" | "enable_download" | "disable_download" | "add_to_playlist" | "remove_from_playlist" | "set_state" | "change_owner" | "copy_media" | "get_ownership" | "set_ownership" | "remove_ownership" | "playlist_membership" | "category_membership" | "tag_membership" | "add_to_category" | "remove_from_category" | "add_tags" | "remove_tags";
                    /** @description List of playlist IDs (required for add_to_playlist and remove_from_playlist actions) */
                    playlist_ids?: number[];
                    /** @description List of category UIDs (required for add_to_category and remove_from_category actions) */
                    category_uids?: string[];
                    /** @description List of tag titles (required for add_tags and remove_tags actions) */
                    tag_titles?: string[];
                    /**
                     * @description State to set (required for set_state action)
                     * @enum {string}
                     */
                    state?: "private" | "public" | "unlisted";
                    /** @description New owner username (required for change_owner action) */
                    owner?: string;
                    /**
                     * @description Ownership type to filter/set/remove (required for get_ownership, set_ownership, and remove_ownership actions)
                     * @enum {string}
                     */
                    ownership_type?: "viewer" | "editor" | "owner";
                    /** @description List of usernames (required for set_ownership and remove_ownership actions) */
                    users?: string[];
                };
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    categories_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description response description */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    comments_list: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description username */
                author?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description response description */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"][];
                };
            };
        };
    };
    encode_profiles_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncodeProfile"][];
                };
            };
        };
    };
    login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** @description username */
                    username?: string;
                    /** @description email */
                    email?: string;
                    /** @description password */
                    password: string;
                };
            };
        };
        responses: {
            /** @description user details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Login"];
                };
            };
            /** @description Bad request */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    manage_comments_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    manage_comments_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    manage_media_list: {
        parameters: {
            query?: {
                /** @description Sort by any of: title, add_date, edit_date, views, likes, reported_times */
                sort_by?: string;
                /** @description Order by: asc, desc */
                ordering?: string;
                /** @description Media state, options: private", "public", "unlisted */
                state?: string;
                /** @description Encoding status, options "pending", "running", "fail", "success" */
                encoding_status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    manage_media_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    manage_users_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    manage_users_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    media_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    media_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["media_create"];
        responses: {
            /** @description response description */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Media"];
                };
            };
            /** @description bad request */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    media_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    media_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["media_create"];
        responses: {
            /** @description response description */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Media"];
                };
            };
            /** @description bad request */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    media_user_bulk_actions_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["media_user_bulk_actions_createData"];
        responses: {
            /** @description Action performed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    media_user_bulk_actions_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["media_user_bulk_actions_createData"];
        responses: {
            /** @description Action performed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    media_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description unique identifier */
                friendly_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SingleMedia"];
                };
            };
            /** @description bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    media_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                friendly_token: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** @description description */
                    description?: string;
                    /** @description title */
                    title?: string;
                    /**
                     * Format: binary
                     * @description media_file
                     */
                    media_file?: string;
                };
            };
        };
        responses: {
            /** @description response description */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Media"];
                };
            };
            /** @description bad request */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    media_manager_actions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description unique identifier */
                friendly_token: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /**
                     * @description action to perform
                     * @enum {string}
                     */
                    type?: "encode" | "review";
                    /** @description if action to perform is encode, need to specify list of ids of encoding profiles */
                    encoding_profiles?: string[];
                    /** @description if action is review, this is the result (True for reviewed, False for not reviewed) */
                    result?: boolean;
                };
            };
        };
        responses: {
            /** @description action created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    media_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description unique identifier */
                friendly_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    media_actions_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                friendly_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    media_actions_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                friendly_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    media_actions_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                friendly_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    media_comments_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                friendly_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    media_comments_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                friendly_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    media_comments_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                friendly_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    media_comments_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                friendly_token: string;
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    media_comments_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                friendly_token: string;
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    media_comments_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                friendly_token: string;
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    playlists_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description response description */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Playlist"][];
                };
            };
        };
    };
    playlists_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    playlists_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description response description */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Playlist"][];
                };
            };
        };
    };
    playlists_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    playlists_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                friendly_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    playlists_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                friendly_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    playlists_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                friendly_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    playlists_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                friendly_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    search_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tags_list: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description response description */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
        };
    };
    user_action_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description action */
                action: "like" | "dislike" | "watch" | "report" | "rate";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    user_token_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_list: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Search by name, username, and optionally email (depending on USER_SEARCH_FIELD setting) */
                name?: string;
                /** @description Exclude current user from results */
                exclude_self?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["users_createData"];
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_list: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Search by name, username, and optionally email (depending on USER_SEARCH_FIELD setting) */
                name?: string;
                /** @description Exclude current user from results */
                exclude_self?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["users_createData"];
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description username */
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** @description action to perform ('change_password' or 'approve_user' or 'disapprove_user') */
                    action: string;
                    /** @description new password (if action is 'change_password') */
                    password?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description username */
                username: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description logo
                     */
                    logo: string;
                    /** @description description */
                    description?: string;
                    /** @description name */
                    name?: string;
                };
            };
        };
        responses: {
            /** @description response description */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetail"];
                };
            };
            /** @description bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_contact_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    whoami_read: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description response description */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetail"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
